#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""CSV 파일을 읽어서 SQL INSERT 파일 생성"""

import csv
import io
import os
import sys

CSV_DIR = r"C:\Users\tae57\OneDrive\바탕 화면\캡스톤\csv"
OUTPUT_FILE = r"C:\Users\tae57\Capston\SafePark\scripts\insert_data.sql"

def read_csv_euckr(filename):
    """EUC-KR 파일을 읽어서 rows 반환"""
    path = os.path.join(CSV_DIR, filename)
    with open(path, 'rb') as f:
        raw = f.read()
    text = raw.decode('euc-kr', errors='replace')
    reader = csv.reader(io.StringIO(text))
    rows = list(reader)
    return rows[0], rows[1:]  # header, data

def read_csv_utf8bom(filename):
    """UTF-8 BOM 파일 읽기"""
    path = os.path.join(CSV_DIR, filename)
    with open(path, encoding='utf-8-sig') as f:
        reader = csv.reader(f)
        rows = list(reader)
    return rows[0], rows[1:]

def escape_sql(value):
    """SQL 문자열 이스케이프"""
    if value is None or value.strip() == '':
        return 'NULL'
    return "'" + value.replace("'", "''") + "'"

lines = []
lines.append("-- SafePark 데이터 적재 SQL")
lines.append("-- Generated by generate_sql.py")
lines.append("")

# ============================================================
# 1. parking_lot 테이블 - 의왕시 주차장
# ============================================================
lines.append("-- ============================================================")
lines.append("-- 1. parking_lot 테이블 (의왕시 주차장)")
lines.append("-- ============================================================")
lines.append("TRUNCATE TABLE parking_lot RESTART IDENTITY CASCADE;")
lines.append("")

try:
    header, rows = read_csv_utf8bom("경기도 의왕시_주차장 현황(보행안전지수)_20221202.csv")
    # 헤더: 공간지리식별번호, ..., 주차장명, ..., 주차면수, ..., 위도, 경도
    # 인덱스 찾기
    h = [x.strip() for x in header]

    name_idx = h.index('주차장명') if '주차장명' in h else 7
    lat_idx = h.index('위도') if '위도' in h else 21
    lng_idx = h.index('경도') if '경도' in h else 22
    capacity_idx = h.index('주차면수') if '주차면수' in h else 11

    count = 0
    for row in rows:
        if len(row) <= max(name_idx, lat_idx, lng_idx):
            continue
        name = row[name_idx].strip()
        lat = row[lat_idx].strip()
        lng = row[lng_idx].strip()
        capacity_str = row[capacity_idx].strip() if len(row) > capacity_idx else ''

        if not lat or not lng or not name:
            continue
        try:
            lat_f = float(lat)
            lng_f = float(lng)
            capacity = int(float(capacity_str)) if capacity_str else 0
        except ValueError:
            continue

        lines.append(
            f"INSERT INTO parking_lot (lot_name, lat, lng, total_spaces, available_spaces) "
            f"VALUES ({escape_sql(name)}, {lat_f}, {lng_f}, {capacity}, {capacity});"
        )
        count += 1

    lines.append(f"-- 주차장 {count}건 적재")
except Exception as e:
    lines.append(f"-- ERROR: 주차장 CSV 처리 실패: {e}")

lines.append("")

# ============================================================
# 2. crack_zone 테이블 - 버스정류장
# ============================================================
lines.append("-- ============================================================")
lines.append("-- 2. crack_zone 테이블 - 버스정류장 (zone_type='BUS_STOP')")
lines.append("-- ============================================================")
lines.append("")

try:
    header, rows = read_csv_utf8bom("경기도 의왕시_정류장 현황(보행안전지수)_20221202.csv")
    h = [x.strip() for x in header]

    name_idx = h.index('정류장명') if '정류장명' in h else 8
    lat_idx = h.index('위도') if '위도' in h else 13
    lng_idx = h.index('경도') if '경도' in h else 14

    count = 0
    for row in rows:
        if len(row) <= max(name_idx, lat_idx, lng_idx):
            continue
        name = row[name_idx].strip()
        lat = row[lat_idx].strip()
        lng = row[lng_idx].strip()

        if not lat or not lng or not name:
            continue
        try:
            lat_f = float(lat)
            lng_f = float(lng)
        except ValueError:
            continue

        lines.append(
            f"INSERT INTO crack_zone (zone_name, lat, lng, zone_type) "
            f"VALUES ({escape_sql(name)}, {lat_f}, {lng_f}, 'BUS_STOP');"
        )
        count += 1

    lines.append(f"-- 버스정류장 {count}건 적재")
except Exception as e:
    lines.append(f"-- ERROR: 정류장 CSV 처리 실패: {e}")

lines.append("")

# ============================================================
# 3. crack_zone 테이블 - 어린이보호구역 (경기도만)
# ============================================================
lines.append("-- ============================================================")
lines.append("-- 3. crack_zone 테이블 - 어린이보호구역 (경기도, zone_type='SCHOOL_ZONE')")
lines.append("-- ============================================================")
lines.append("")

try:
    header, rows = read_csv_euckr("전국어린이보호구역표준데이터.csv")
    # 헤더: 시설종류, 대상시설명, 소재지도로명주소, 소재지지번주소, 위도, 경도, ...

    lat_idx = 4
    lng_idx = 5
    name_idx = 1  # 대상시설명
    addr_idx = 2  # 도로명주소 (경기도 필터용)

    count = 0
    for row in rows:
        if len(row) <= max(lat_idx, lng_idx, addr_idx):
            continue

        addr = row[addr_idx].strip()
        # 의왕시만 필터링
        if '의왕' not in addr:
            continue

        name = row[name_idx].strip()
        lat = row[lat_idx].strip()
        lng = row[lng_idx].strip()

        if not lat or not lng:
            continue
        try:
            lat_f = float(lat)
            lng_f = float(lng)
        except ValueError:
            continue

        lines.append(
            f"INSERT INTO crack_zone (zone_name, lat, lng, zone_type) "
            f"VALUES ({escape_sql(name)}, {lat_f}, {lng_f}, 'SCHOOL_ZONE');"
        )
        count += 1

    lines.append(f"-- 어린이보호구역(경기도) {count}건 적재")
except Exception as e:
    lines.append(f"-- ERROR: 어린이보호구역 CSV 처리 실패: {e}")

lines.append("")

# ============================================================
# 4. crack_zone 테이블 - 무인단속카메라 (경기도만)
# ============================================================
lines.append("-- ============================================================")
lines.append("-- 4. crack_zone 테이블 - 무인단속카메라 (경기도, zone_type='CCTV')")
lines.append("-- ============================================================")
lines.append("")

try:
    header, rows = read_csv_euckr("전국무인교통단속카메라표준데이터.csv")
    # 헤더: 무인교통단속카메라관리번호, 시도명, 시군구명, 읍면동명, 도로노선번호, 도로노선명, 도로노선방향, 소재지도로명주소, 소재지지번주소, 위도, 경도, ...

    lat_idx = 9
    lng_idx = 10
    name_idx = 7  # 소재지도로명주소
    sido_idx = 1  # 시도명 (경기도 필터용)
    gungu_idx = 2  # 시군구명 (의왕시 필터 선택적)

    count = 0
    for row in rows:
        if len(row) <= max(lat_idx, lng_idx):
            continue

        sido = row[sido_idx].strip() if len(row) > sido_idx else ''
        gungu = row[gungu_idx].strip() if len(row) > gungu_idx else ''
        # 의왕시만 필터링
        if '의왕' not in gungu:
            continue

        name = row[name_idx].strip() if len(row) > name_idx else ''
        if not name:
            name = '무인단속카메라'
        lat = row[lat_idx].strip()
        lng = row[lng_idx].strip()

        if not lat or not lng:
            continue
        try:
            lat_f = float(lat)
            lng_f = float(lng)
        except ValueError:
            continue

        lines.append(
            f"INSERT INTO crack_zone (zone_name, lat, lng, zone_type) "
            f"VALUES ({escape_sql(name)}, {lat_f}, {lng_f}, 'CCTV');"
        )
        count += 1

    lines.append(f"-- 무인단속카메라(경기도) {count}건 적재")
except Exception as e:
    lines.append(f"-- ERROR: 무인단속카메라 CSV 처리 실패: {e}")

lines.append("")
lines.append("-- 완료")

# 파일 저장 (UTF-8)
with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"SQL 파일 생성 완료: {OUTPUT_FILE}")
print(f"총 {len(lines)} 라인")
